// Generated by CoffeeScript 1.9.3
(function() {
  describe("sbj:journals", function() {
    return it('should export an angular module "shareBJ.journals"', function() {
      return expect(angular.module('shareBJ.journals').toBeDefined());
    });
  });

}).call(this);

//# sourceMappingURL=journals_specs.js.map
