// Generated by CoffeeScript 1.9.3
(function() {
  describe('sbj:users', function() {
    return it("should have the imported 'ShareBJ' variable", function() {
      return expect(ShareBJ).toBeDefined();
    });
  });

}).call(this);

//# sourceMappingURL=users_spec.js.map
