// Generated by CoffeeScript 1.9.3
(function() {
  describe('sbj:lib', function() {
    it("should have 'ShareBJ' variable", function() {
      return expect(ShareBJ).toBeDefined();
    });
    describe('ShareBJ', function() {
      it("should have a 'VERSION'", function() {
        return expect(ShareBJ.VERSION).toBeDefined();
      });
      it("should have 'schemas'", function() {
        return expect(ShareBJ.schemas).toBeDefined();
      });
      return it("should have a 'allowCheck' method", function() {
        return expect(ShareBJ.allowCheck).toBeDefined();
      });
    });
    describe("Meteor.Collection", function() {
      it("should have a 'addField' method", function() {
        return expect(Meteor.Collection.prototype.addField).toBeDefined();
      });
      it("should have a 'removeField' method", function() {
        return expect(Meteor.Collection.prototype.removeField).toBeDefined();
      });
      return it("should have a 'removeField' method", function() {
        return expect(Meteor.Collection.prototype.allowCheck).toBeDefined();
      });
    });
    return describe("SimpleSchema", function() {
      it("should have a 'getEditableFields' method", function() {
        return expect(SimpleSchema.prototype.getEditableFields).toBeDefined();
      });
      it("should have a 'getPublicFields' method", function() {
        return expect(SimpleSchema.prototype.getPublicFields).toBeDefined();
      });
      return it("should have a 'getProfileFields' method", function() {
        return expect(SimpleSchema.prototype.getProfileFields).toBeDefined();
      });
    });
  });

}).call(this);

//# sourceMappingURL=lib_spec.js.map
