// Generated by CoffeeScript 1.9.3
(function() {
  describe('sbj:lib', function() {
    return it('should have a angular module sharebj.lib', function() {
      return expect(angular.module('shareBJ.lib')).toBeDefined();
    });
  });

}).call(this);

//# sourceMappingURL=libSpec.js.map
