// Generated by CoffeeScript 1.9.3
(function() {
  describe("sbj:users", function() {
    beforeEach(angular.mock.module('shareBJ.users'));
    return describe("LoginCtrl", function() {
      var $controller, $location, $rootScope, $scope, $state;
      $controller = null;
      $rootScope = null;
      $location = null;
      $scope = null;
      $state = null;
      beforeEach(angular.mock.inject(function(_$rootScope_, _$controller_, _$state_, _$location_, $templateCache) {
        $controller = _$controller_;
        $rootScope = _$rootScope_;
        $location = _$location_;
        $state = _$state_;
        $scope = $rootScope.$new();
        return $templateCache.put('login.ng.html', '');
      }));
      return describe('$scope.login', function() {
        return it('should have a valid user logged in', function() {
          var loginCtrl;
          loginCtrl = $controller('LoginCtrl', {
            $scope: $scope
          });
          $state.go('users_login');
          $rootScope.$digest();
          $scope.username = 'test_user';
          $scope.password = '123456';
          $scope.login();
          expect($state.current.name).toBe('users_login');
          return expect($location.path()).toBe('/login');
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=users_spec.js.map
